version: '3.7'
services:
    warsehouse:
        image: postgres:10
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
        logging:
            options:
                max-size: 10m
                max-file: "3"
